# @package model

_target_: src.models.simclr.SimCLR

base_model: "resnet50"
pretrained: true
projection_dim: ${model.projection_dim}
hidden_dim: ${model.hidden_dim}
temperature: ${model.temperature}
freeze_backbone: false
